resources:
  repositories:
    - repository: templateRepo
      type: git
      name: azure-devops-templates
      ref: refs/tags/1.0.45
    - repository: azure-tf-foundation
      type: git
      name: azure-tf-foundation

parameters:
- name: skipApply
  displayName: Skip Apply?
  type: boolean
  default: false

name: terraform

pool:
  vmImage: 'ubuntu-latest'

pr:
  autoCancel: false
  branches:
    include:
      - main

trigger:
  branches:
    include:
      - main

variables:
- name: working_directory
  value: ./

stages:
- template: test-stage/terraform.yaml@templateRepo
  parameters:
    name: Validate

- ${{ if or(eq(variables['Build.SourceBranch'], 'refs/heads/main'), eq(variables['Build.Reason'], 'PullRequest'), eq(variables['Build.Reason'], 'Manual')) }}:
  - template: release-stage/terraform-with-lock-toggle.yaml@templateRepo
    parameters:
      name: Development
      env_path: dev
      service_connection: scn-sub-cdp-preprd-we-001
      skip_apply: ${{ parameters.skipApply }}
      dependsOn: Validate
      agent_pool_name: cdp-runners-prd
      storage_account_resource_group_name: rg-ingestion-cdp-preprd-we-ojsu
      storage_account_name: stingcdppreprddevweojsu

- ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/main') }}:
  - template: release-stage/terraform-with-lock-toggle.yaml@templateRepo
    parameters:
      name: Test
      env_path: tst
      service_connection: scn-sub-cdp-preprd-we-001
      skip_apply: ${{ parameters.skipApply }}
      dependsOn: Development
      agent_pool_name: cdp-runners-prd
      storage_account_resource_group_name: rg-ingestion-cdp-preprd-we-ojsu
      storage_account_name: stingcdppreprdtstweojsu

- ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/main') }}:
  - template: release-stage/terraform-with-lock-toggle.yaml@templateRepo
    parameters:
      name: Acceptance
      env_path: acp
      service_connection: scn-sub-cdp-preprd-we-001
      skip_apply: ${{ parameters.skipApply }}
      dependsOn: Test
      agent_pool_name: cdp-runners-prd
      storage_account_resource_group_name: rg-ingestion-cdp-preprd-we-ojsu
      storage_account_name: stingcdppreprdacpweojsu
