resources:
  repositories:
    - repository: templateRepo
      type: git
      name: azure-devops-templates
      ref: refs/tags/1.0.45
    - repository: azure-tf-foundation
      type: git
      name: azure-tf-foundation

name: terraform-prod-release

pool:
  vmImage: 'ubuntu-latest'

pr:
  autoCancel: false

trigger:
  tags:
    include:
    - '*'

variables:
- name: working_directory
  value: ./

stages:
- template: test-stage/terraform.yaml@templateRepo
  parameters:
    name: Validate
# csf:3.3.11a:Manual approval to release to Production
- template: utils/approval.yaml@templateRepo
  parameters:
    name: approve_release_to_production
    dependsOn: Validate
    approval_environment: production-approvers-infra
# only release from tag, or a manual run which disables apply
- ${{ if or(startsWith(variables['Build.SourceBranch'], 'refs/tags/'), eq(variables['Build.Reason'], 'Manual')) }}:
  - template: release-stage/terraform-with-lock-toggle.yaml@templateRepo
    parameters:
      name: Production
      env_path: prd
      service_connection: scn-cdp-prd-we-001
      skip_apply: ${{ eq(variables['Build.Reason'], 'Manual') }}
      dependsOn: approve_release_to_production
      agent_pool_name: cdp-runners-prd
      storage_account_resource_group_name: rg-ingestion-cdp-prd-we-kutk
      storage_account_name: stingcdpprdprdwekutk
