resources:
  repositories:
    - repository: templateRepo
      type: git
      name: azure-devops-templates
      ref: refs/tags/1.0.33

trigger: none

stages:
- template: utils/tag.yaml@templateRepo
  parameters:
    major: 1
    minor: 1
