pipeline_name: pl_basel_iv_orchestration
pipeline_parameters:
  dbx_workspace_url: https://adb-3918317864916071.11.azuredatabricks.net
  dbx_job_id_check: 504510887107468
  dbx_job_id_model: 906832576155181
  fileserver_host_name: \\SVNIBCFILP101\E
  fileserver_user_name: PRD\SRV_AA_PRD
  fileserver_credentials_secret_name: fileserver-credentials-ods
  fileserver_directory: Interfac\AA\aa_retail\Monthly\IRB
  sink_file_name_template: basel_4_model_output_cdp_{period_end_date}.csv
